package org.jammor9.worldsim.worldgenerator;

public enum Biome {
    TROPICAL,
    OCEAN,
    HOT_DESERT,
    SAVANNAH,
    HUMID_CONTINENTAL,
    SUBARCTIC_CONTINENTAL,
    TEMPERATE_FOREST,
    BOREAL_FOREST,
    COLD_DESERT,
    TUNDRA,
    COLD_STEPPE,
    HOT_STEPPE,
    ICE,
    GRASSLAND,
    SEASONAL_FOREST,
    WOODLAND,
    TEMPERATE_RAINFOREST,
    DESERT,
}
